title: Blog by A.M.D. Srinivas
description: > # this means to ignore newlines until "baseurl:"
  This blog contains my experiences and tutorials on Machine learning, Deep Learning and Computer Software.
permalink: ':title/'
baseurl: "/test_blog" # the subpath of your site, e.g. /blog
url: "https://amdsrinivas.github.io/test_blog" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: A M D Srinivas # add your name
author-img: avatar.jpg # add your photo
about-author:  # add description
#social-twitter: # add your Twitter handle
#social-facebook: # add your Facebook handle
social-github: amdsrinivas # add your Github handle
social-linkedin: amdsrinivas # add your Linkedin handle
#social-email: amd.srinivas@gmail.com # add your Email address

# Disqus
discus-identifier: amdsrinivas-github-io # add your discus identifier

# Tracker
analytics: UA-126034999-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
